version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo Installing dependencies...
      - npm install --legacy-peer-deps

  build:
    commands:
      - echo Building the Next.js application...
      - npm run build

artifacts:
  files:
    - '**/*'
  base-directory: .next

cache:
  paths:
    - 'node_modules/**/*'